name: merchant_app
description: "Merchant App for Auto Parking Management"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.2.2
  intl: ^0.19.0
  pdf: ^3.8.4
  path_provider: ^2.0.15
  open_file: ^3.3.2
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  fl_chart: ^0.69.2
  camera: ^0.10.5+9
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  flutter_secure_storage: ^9.2.2
  path: ^1.9.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  nfc_manager: ^3.5.0
  flutter_cache_manager: ^3.4.1
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^11.3.3
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  permission_handler: ^11.4.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/citypark_doodle.jpg

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

